inference_address=http://127.0.0.1:8080
management_address=http://127.0.0.1:8081
number_of_netty_threads=4
job_queue_size=10
model_store=model-store
workflow_store=model-store
enable_auth_token=false 
log_level=INFO